apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-processing-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-processing-service
  template:
    metadata:
      labels:
        app: data-processing-service
    spec:
      containers:
      - name: data-processing-container
        image: data-processing-service:v1
        command: ["./data-processing"]
        resources:
          requests:
            memory: "1Gi"
            cpu: "0.5"
          limits:
            memory: "2Gi"
            cpu: "1"
