apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-processing-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-processing-service
  template:
    metadata:
      labels:
        app: data-processing-service
    spec:
      containers:
      - name: data-processing-container
        image: data-processing-service:v1
        command: ["./data-processing"]
        resources:
          requests:
            memory: "1Gi"
            cpu: "0.5"
          limits:
            memory: "2Gi"
            cpu: "1"
        env:
        - name: AUTH_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: data-processing-configmap
              key: AUTH_SERVICE_URL
        - name: INVENTORY_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: data-processing-configmap
              key: INVENTORY_SERVICE_URL
        - name: MESSAGE_QUEUE_URL
          valueFrom:
            configMapKeyRef:
              name: data-processing-configmap
              key: MESSAGE_QUEUE_URL
        - name: OTHER_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: data-processing-configmap
              key: OTHER_SERVICE_URL
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: data-processing-configmap
              key: DATABASE_URL
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_HOST
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_PASSWORD
