apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-service
  template:
    metadata:
      labels:
        app: api-service
    spec:
      containers:
      - name: api-container
        image: api-service:v1
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "2Gi"
            cpu: "0.5"
          limits:
            memory: "4Gi"
            cpu: "1"
        env:
        - name: AUTH_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: api-configmap
              key: AUTH_SERVICE_URL
        - name: INVENTORY_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: api-configmap
              key: INVENTORY_SERVICE_URL
        - name: MESSAGE_QUEUE_URL
          valueFrom:
            configMapKeyRef:
              name: api-configmap
              key: MESSAGE_QUEUE_URL
        - name: OTHER_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: api-configmap
              key: OTHER_SERVICE_URL
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: api-configmap
              key: DATABASE_URL
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: api-configmap
              key: DB_HOST
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: api-configmap
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_PASSWORD
